import os

APP_ROOT = os.path.dirname(os.path.abspath(__file__))
STATIC_PATH = os.path.join(APP_ROOT, "static/")
JS_PATH = os.path.join(STATIC_PATH, "js/")
IMAGE_PATH = os.path.join(STATIC_PATH, "images/")
CONTENT_IMAGE_PATH = os.path.join(IMAGE_PATH, "content_image.jpg")
STYLE_IMAGE_PATH = os.path.join(IMAGE_PATH, "style_image.jpg")
MASK_PATH = os.path.join(STATIC_PATH, "masks/")
OUTPUT_PATH = os.path.join(STATIC_PATH, "output/")
OUTPUT_IMAGE_PATH = os.path.join(OUTPUT_PATH, "output.jpg")
CONTENT_MASK_PATH = os.path.join(MASK_PATH, "content/")
STYLE_MASK_PATH = os.path.join(MASK_PATH, "style/")
CONTENT_COMBINED_MASK_PATH = os.path.join(CONTENT_MASK_PATH, "content_combined_mask.jpg")
STYLE_COMBINED_MASK_PATH = os.path.join(STYLE_MASK_PATH, "style_combined_mask.jpg")
CONTENT_THRESHOLD_MASK_PATH = os.path.join(CONTENT_MASK_PATH, "content_threshold_mask.jpg")
STYLE_THRESHOLD_MASK_PATH = os.path.join(STYLE_MASK_PATH, "style_threshold_mask.jpg")
CONTENT_COLOUR_MASK_PATH = os.path.join(CONTENT_MASK_PATH, "content_colour_mask.jpg")
STYLE_COLOUR_MASK_PATH = os.path.join(STYLE_MASK_PATH, "style_colour_mask.jpg")
SUMMARY_PATH = os.path.join(STATIC_PATH, "summary/")
SUMMARY_FILE_PATH = os.path.join(SUMMARY_PATH, "info.txt")